sudo: false
env:
  global:
    secure: BFkVp5pMBoDRLifsnv/BnVJa0C43upgcJtxhJ5N3RyEP0lo+xzdwGVnys+/RQAYQJuKpQnb4lNhVbnuCpJHhn5hjjOajKQaboNg31FCJK6e4l+f3eU2tX+yoClll5asxWFjrmpvipaJUHdRX4+jbcuugMj98iVn2drXYEx5WzmBkif2grYnUh2ZLm0587N8yZT8cD+ycb68jyws9u12cQWuukvGXKDhYbaENLqeiDU2wQlPsZ4LmeNt4acR89TxMuLBDtkg409kxox1ahaROZhiTgGJ+xiftAoErWMzSWuP1wAf52tYuyM2xk0WMhid2S1UftAaPDv2QFsfLWGjhKLHvdQrEoDSN0EThNxWiqQR3V7e0Z1N4K4Y+ENVqdGz+Z/tCvQGlck/rwZyM3PYqU+M0wfGH+U6ZYF1+Bbh/6spGP950AdUvFO0FnQhSFrxciwkNT1W2OIsd9z8VuBg5AGLhxOa92kBFkrP744kAheDOxHzij45aZn71X4peGl6Xz7FxMbdOjBcWaW6Ee64NLhO7vDBtGkl2LiAm5UH4BTK/a5aSlUaH4nyUMSbWgzCEUjHCGiuQszFIzk1okMQvTisEMBgsgRqd40hzDSkX37Cbka2yFLf9TbHBBM0F9Mfe7/QFGTGgtumcXFpVO6Wbulolv40Gm/sX1D/UWVEBfVw=
addons:
  apt:
    packages:
    - jq
    - git
language: python
os:
- linux
script:
- python ./queue.py --token $REPORT_CI_TOKEN --name "Only queued"  --title "Queue test" > /dev/null
- python ./queue.py --token $REPORT_CI_TOKEN --name "Queue -> InProgress"  --title "Progress test" | grep -E '^\s*\{\s*"id"\s*:\s*([0-9]+)\s*\}\s*$' > job1.json
- JOB1=$(jq '.id' < job1.json)
- echo "JOB1  https://github.com/report-ci/scripts/runs/$JOB1"
- python ./queue.py --token $REPORT_CI_TOKEN -x ./README.md --name "Queue -> Cancelled"  --title "Cancel test" | grep -E '^\s*\{\s*"id"\s*:\s*([0-9]+)\s*\}\s*$' > job2.json
- JOB2=$(jq '.id' < job2.json)
- echo "JOB2  https://github.com/report-ci/scripts/runs/$JOB2"
- python ./start.py --token $REPORT_CI_TOKEN --check_run $JOB1
- echo "Started JOB1"
- python ./start.py --token $REPORT_CI_TOKEN --name "Start -> Cancelled"  --title "Cancel test 2"| grep -E '^\s*\{\s*"id"\s*:\s*([0-9]+)\s*\}\s*$' > job3.json
- JOB3=$(jq '.id' < job3.json)
- echo "JOB3  https://github.com/report-ci/scripts/runs/$JOB3"
- python ./cancel.py --token $REPORT_CI_TOKEN --check_run $JOB2
- echo "Cancelled JOB2"
- python ./cancel.py --token $REPORT_CI_TOKEN --check_run $JOB3
- echo "Cancelled JOB3"
