sudo: false
env:
  global:
    secure: BFkVp5pMBoDRLifsnv/BnVJa0C43upgcJtxhJ5N3RyEP0lo+xzdwGVnys+/RQAYQJuKpQnb4lNhVbnuCpJHhn5hjjOajKQaboNg31FCJK6e4l+f3eU2tX+yoClll5asxWFjrmpvipaJUHdRX4+jbcuugMj98iVn2drXYEx5WzmBkif2grYnUh2ZLm0587N8yZT8cD+ycb68jyws9u12cQWuukvGXKDhYbaENLqeiDU2wQlPsZ4LmeNt4acR89TxMuLBDtkg409kxox1ahaROZhiTgGJ+xiftAoErWMzSWuP1wAf52tYuyM2xk0WMhid2S1UftAaPDv2QFsfLWGjhKLHvdQrEoDSN0EThNxWiqQR3V7e0Z1N4K4Y+ENVqdGz+Z/tCvQGlck/rwZyM3PYqU+M0wfGH+U6ZYF1+Bbh/6spGP950AdUvFO0FnQhSFrxciwkNT1W2OIsd9z8VuBg5AGLhxOa92kBFkrP744kAheDOxHzij45aZn71X4peGl6Xz7FxMbdOjBcWaW6Ee64NLhO7vDBtGkl2LiAm5UH4BTK/a5aSlUaH4nyUMSbWgzCEUjHCGiuQszFIzk1okMQvTisEMBgsgRqd40hzDSkX37Cbka2yFLf9TbHBBM0F9Mfe7/QFGTGgtumcXFpVO6Wbulolv40Gm/sX1D/UWVEBfVw=
addons:
  apt:
    packages:
    - git
language: python
os:
- linux
script:
- python ./queue.py --name "Only queued"  --title "Queue test"
- python ./queue.py --name "Queue -> InProgress"  --title "Progress test" --id_file .job1.json
- python ./queue.py -x ./README.md --name "Queue -> Cancelled"  --title "Cancel test" --id_file .job2.json
- python ./start.py --id_file .job1.json
- python ./start.py --name "Start -> Cancelled"  --title "Cancel test 2" --id_file .job3.json
- python ./cancel.py --id_file .job2.json
- python ./cancel.py --id_file .job3.json
- python ./queue.py --name "Queue -> Completed" --title "QC Test"
- python ./upload.py 